before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/deps
    binary: codesee-deps-go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
checksum:
  name_template: 'checksums.txt'
release:
  github:
    owner: Codesee-io
    name: codesee-deps-go
